<?php
// Show all PHP errors (helps fix HTTP 500 errors)
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

if (session_status() !== PHP_SESSION_ACTIVE) {
    session_start();
}

$supportedLanguages = ["en", "ar"];
$langParam = $_GET["lang"] ?? "";
if ($langParam && in_array($langParam, $supportedLanguages, true)) {
    $_SESSION["lang"] = $langParam;
}

$lang = $_SESSION["lang"] ?? "en";
if (!in_array($lang, $supportedLanguages, true)) {
    $lang = "en";
}

$isRtl = $lang === "ar";
$dir = $isRtl ? "rtl" : "ltr";

$translations = [
    "en" => [
        "page_title_default" => "Devify",
        "page_title_home" => "Devify | Premium Digital Studio",
        "page_title_login" => "Client Login | Devify",
        "page_title_register" => "Register | Devify",
        "page_title_request" => "Request a Project | Devify",
        "page_title_dashboard" => "Client Dashboard | Devify",
        "page_title_admin_login" => "Admin Login | Devify",
        "page_title_admin_dashboard" => "Admin Dashboard | Devify",
        "nav_services" => "Services",
        "nav_portfolio" => "Portfolio",
        "nav_request" => "Request",
        "nav_admin" => "Admin",
        "nav_dashboard" => "Dashboard",
        "nav_logout" => "Logout",
        "nav_register" => "Register",
        "nav_login" => "Login",
        "lang_toggle_label" => "Language",
        "hero_title" => "We don’t just build websites. We build presence.",
        "hero_lead" => "Devify blends strategy, design, and engineering to launch premium products with a lasting presence.",
        "hero_request_cta" => "Request a project",
        "hero_services_cta" => "Explore services",
        "client_portal" => "Client Portal",
        "client_portal_status" => "Live",
        "client_portal_title" => "Track every milestone in one place.",
        "client_portal_desc" => "Stay aligned with real-time status updates, project highlights, and communication threads.",
        "average_delivery_label" => "Average delivery",
        "client_retention_label" => "Client retention",
        "services_heading" => "Services built for high-growth teams.",
        "services_desc" => "From launch strategy to full-scale engineering, Devify brings boutique attention with enterprise execution.",
        "what_we_do_kicker" => "What we do",
        "what_we_do_title" => "Design, build, and launch modern web experiences.",
        "what_we_do_desc" => "Devify is a small studio helping startups and local businesses go from idea → live product. We combine clean UI, fast development, and reliable backend systems.",
        "what_we_do_card_design_title" => "🎨 Web Design & UI",
        "what_we_do_card_design_desc" => "Dark, modern layouts with polished interaction details.",
        "what_we_do_card_dev_title" => "⚙️ Full-Stack Development",
        "what_we_do_card_dev_desc" => "PHP + MySQL builds with secure auth and dashboards.",
        "what_we_do_card_launch_title" => "🚀 Launch & Support",
        "what_we_do_card_launch_desc" => "Deployment help, fixes, and iterative improvements.",
        "service_strategy_title" => "Product Strategy",
        "service_strategy_desc" => "Roadmapping, market insights, and launch planning tailored to your growth.",
        "service_design_title" => "Design & UX",
        "service_design_desc" => "Minimal, sophisticated interfaces with signature motion and polish.",
        "service_delivery_title" => "Full-stack Delivery",
        "service_delivery_desc" => "PHP 8 + MySQL architecture, built for performance, security, and scale.",
        "portfolio_heading" => "Portfolio",
        "portfolio_kicker" => "Curated for ambitious brands.",
        "portfolio_details_heading" => "Portfolio highlights",
        "portfolio_details_intro" => "Deep dives into the craft, build process, and outcomes for each launch.",
        "portfolio_gallery_label" => "UI snapshots",
        "portfolio_build_label" => "How it was made",
        "portfolio_timeline_label" => "Timeline",
        "portfolio_satisfaction_label" => "Client satisfaction",
        "portfolio_bean_title" => "Bean & Brew",
        "portfolio_bean_summary" => "A refined ordering experience that keeps coffee lovers moving from menu to pickup without friction.",
        "portfolio_bean_build" => "We mapped the customer flow, created a high-contrast UI kit, and connected it to a streamlined pickup workflow so baristas could fulfill orders in seconds.",
        "portfolio_bean_timeline" => "6 weeks from discovery to launch",
        "portfolio_bean_satisfaction" => "97% satisfaction from the pilot store group",
        "work_lumen_desc" => "A smooth online ordering experience designed for fast service and great coffee momenrts.",
        "portfolio_evo_title" => "EvoEvents",
        "portfolio_evo_summary" => "An event planning studio with drag-and-drop scheduling, vendor coordination, and guest-ready timelines.",
        "portfolio_evo_build" => "We crafted an interactive planning canvas, built a collaborative task system, and delivered a clean admin suite for event coordinators.",
        "portfolio_evo_timeline" => "8 weeks with weekly stakeholder demos",
        "portfolio_evo_satisfaction" => "94% satisfaction across beta organizers",
        "work_astral_desc" => "An interactive event planning platform designed to turn ideas into memorable experiences.",
        "portfolio_estate_title" => "EstateFlow",
        "portfolio_estate_summary" => "A management hub for property managers who need visibility across tenants, payments, and maintenance.",
        "portfolio_estate_build" => "We unified lease tracking, maintenance intake, and reporting into a single dashboard with role-based access for on-site teams.",
        "portfolio_estate_timeline" => "7 weeks from kickoff to rollout",
        "portfolio_estate_satisfaction" => "96% satisfaction from property ops teams",
        "work_signal_desc" => "A modern system designed to manage properties, tenants, and operations efficiently",
        "footer_heading" => "Ready to build your next release?",
        "footer_desc" => "Partner with Devify for a premium digital experience.",
        "footer_cta" => "Start a project",
        "label_email" => "Email",
        "label_password" => "Password",
        "label_full_name" => "Full name",
        "login_heading" => "Welcome back.",
        "login_subheading" => "Sign in to access your client portal.",
        "login_button" => "Login",
        "login_new_prompt" => "New to Devify?",
        "login_new_link" => "Create account",
        "error_invalid_credentials" => "Invalid credentials.",
        "register_heading" => "Create your client portal.",
        "register_subheading" => "Join Devify to start submitting project requests.",
        "register_success" => "Registration complete. You can now log in.",
        "register_error_required" => "All fields are required.",
        "register_error_exists" => "An account with this email already exists.",
        "register_error_failed" => "Registration failed. Please try again.",
        "register_button" => "Register",
        "register_login_prompt" => "Already have an account?",
        "register_login_link" => "Login",
        "request_heading" => "Start your next build.",
        "request_subheading" => "Tell us about your product vision and we will respond within 24 hours.",
        "request_success" => "Project request submitted successfully.",
        "request_error" => "Please provide a project title and details.",
        "request_error_failed" => "Unable to submit your request. Please try again.",
        "request_title_label" => "Project name",
        "request_title_placeholder" => "e.g. Premium SaaS redesign",
        "request_budget_label" => "Estimated budget",
        "request_budget_placeholder" => "$10k - $30k",
        "request_timeline_label" => "Ideal timeline",
        "request_timeline_placeholder" => "6-8 weeks",
        "request_details_label" => "Project details",
        "request_details_placeholder" => "Describe your goals, features, and expectations.",
        "request_submit_button" => "Submit request",
        "contact_heading" => "Contact us",
        "contact_subheading" => "Tell us about your project goals and we will respond within 24 hours.",
        "contact_name_label" => "Name",
        "contact_name_placeholder" => "Your full name",
        "contact_email_label" => "Email",
        "contact_email_placeholder" => "you@example.com",
        "contact_message_label" => "Message",
        "contact_message_placeholder" => "Share a quick summary of what you need.",
        "contact_submit" => "Send message",
        "dashboard_welcome" => "Welcome, {name}.",
        "dashboard_subheading" => "Track your project requests and current status.",
        "dashboard_new_request" => "New request",
        "dashboard_table_project" => "Project",
        "dashboard_table_budget" => "Budget",
        "dashboard_table_timeline" => "Timeline",
        "dashboard_table_status" => "Status",
        "dashboard_table_submitted" => "Submitted",
        "dashboard_empty" => "No requests yet. Submit your first project brief.",
        "admin_login_heading" => "Admin access",
        "admin_login_subheading" => "Manage incoming project requests.",
        "admin_login_button" => "Login",
        "admin_dashboard_heading" => "Admin overview",
        "admin_dashboard_subheading" => "Manage every incoming request across the portfolio.",
        "admin_total_requests" => "{count} total requests",
        "admin_status_updated" => "Status updated.",
        "admin_table_client" => "Client",
        "admin_table_project" => "Project",
        "admin_table_budget" => "Budget",
        "admin_table_timeline" => "Timeline",
        "admin_table_status" => "Status",
        "admin_table_update" => "Update",
        "admin_empty" => "No project requests yet.",
        "admin_save_button" => "Save",
        "status_submitted" => "Submitted",
        "status_reviewing" => "Reviewing",
        "status_in_progress" => "In Progress",
        "status_completed" => "Completed"
    ],
    "ar" => [
        "page_title_default" => "ديفاي",
        "page_title_home" => "ديفاي | استوديو رقمي فاخر",
        "page_title_login" => "تسجيل دخول العملاء | ديفاي",
        "page_title_register" => "إنشاء حساب | ديفاي",
        "page_title_request" => "طلب مشروع | ديفاي",
        "page_title_dashboard" => "لوحة تحكم العميل | ديفاي",
        "page_title_admin_login" => "تسجيل دخول الإدارة | ديفاي",
        "page_title_admin_dashboard" => "لوحة تحكم الإدارة | ديفاي",
        "nav_services" => "الخدمات",
        "nav_portfolio" => "الأعمال",
        "nav_request" => "طلب مشروع",
        "nav_admin" => "الإدارة",
        "nav_dashboard" => "لوحة التحكم",
        "nav_logout" => "تسجيل الخروج",
        "nav_register" => "إنشاء حساب",
        "nav_login" => "تسجيل الدخول",
        "lang_toggle_label" => "اللغة",
        "hero_title" => "تجارب رقمية داكنة وعصرية لا تُنسى.",
        "hero_lead" => "تمزج ديفاي بين الاستراتيجية والتصميم والهندسة لإطلاق منتجات فاخرة بحضور يدوم.",
        "hero_request_cta" => "اطلب مشروعًا",
        "hero_services_cta" => "استكشف الخدمات",
        "client_portal" => "بوابة العملاء",
        "client_portal_status" => "متصل الآن",
        "client_portal_title" => "تابع كل مرحلة في مكان واحد.",
        "client_portal_desc" => "ابقَ على اطلاع بتحديثات الحالة الفورية وأبرز المراحل وخيوط التواصل.",
        "average_delivery_label" => "متوسط التسليم",
        "client_retention_label" => "الاحتفاظ بالعملاء",
        "services_heading" => "خدمات مصممة لفرق النمو السريع.",
        "services_desc" => "من استراتيجية الإطلاق إلى التنفيذ الهندسي، تمنحك ديفاي اهتمامًا بوتيكيًا وتنفيذًا مؤسسيًا.",
        "what_we_do_kicker" => "ماذا نفعل",
        "what_we_do_title" => "نصمم ونبني ونطلق تجارب ويب حديثة.",
        "what_we_do_desc" => "ديفاي استوديو صغير يساعد الشركات الناشئة والأعمال المحلية على الانتقال من الفكرة إلى المنتج الحي. نجمع بين واجهات نظيفة وتطوير سريع وأنظمة خلفية موثوقة.",
        "what_we_do_card_design_title" => "🎨 تصميم الويب وتجربة المستخدم",
        "what_we_do_card_design_desc" => "تصاميم داكنة وعصرية مع تفاصيل تفاعل مصقولة.",
        "what_we_do_card_dev_title" => "⚙️ تطوير متكامل",
        "what_we_do_card_dev_desc" => "بناءات PHP + MySQL مع مصادقة آمنة ولوحات تحكم.",
        "what_we_do_card_launch_title" => "🚀 الإطلاق والدعم",
        "what_we_do_card_launch_desc" => "مساعدة في النشر والإصلاحات والتحسينات المستمرة.",
        "service_strategy_title" => "استراتيجية المنتج",
        "service_strategy_desc" => "خارطة طريق، ورؤى سوقية، وتخطيط إطلاق مخصص لنموك.",
        "service_design_title" => "التصميم وتجربة المستخدم",
        "service_design_desc" => "واجهات بسيطة وراقية مع حركة متقنة ولمسات نهائية.",
        "service_delivery_title" => "تسليم شامل",
        "service_delivery_desc" => "هيكل PHP 8 + MySQL مبني للأداء والأمان والتوسع.",
        "portfolio_heading" => "نماذج مختارة",
        "portfolio_kicker" => "منسّقة للعلامات الطموحة.",
        "portfolio_details_heading" => "أبرز الأعمال",
        "portfolio_details_intro" => "تفاصيل عن أسلوب التنفيذ والنتائج لكل إطلاق.",
        "portfolio_gallery_label" => "لقطات واجهة المستخدم",
        "portfolio_build_label" => "طريقة التنفيذ",
        "portfolio_timeline_label" => "المدة الزمنية",
        "portfolio_satisfaction_label" => "رضا العملاء",
        "portfolio_bean_title" => "Bean & Brew",
        "portfolio_bean_summary" => "تجربة طلب أنيقة تنقل العملاء من القائمة إلى الاستلام بسلاسة.",
        "portfolio_bean_build" => "حددنا رحلة العميل، وأنشأنا نظام واجهة عالي التباين، وربطناه بسير عمل سريع للطلبات.",
        "portfolio_bean_timeline" => "6 أسابيع من الاكتشاف حتى الإطلاق",
        "portfolio_bean_satisfaction" => "نسبة رضا 97٪ من المتاجر التجريبية",
        "work_lumen_desc" => "تجربة طلب إلكترونية سلسة لخدمة سريعة ولحظات قهوة رائعة.",
        "portfolio_evo_title" => "EvoEvents",
        "portfolio_evo_summary" => "منصة تخطيط فعاليات تفاعلية مع جدولة وتعاون واضح.",
        "portfolio_evo_build" => "صممنا لوحة تخطيط تفاعلية وبنينا نظام مهام تعاوني ولوحة تحكم أنيقة للمنظمين.",
        "portfolio_evo_timeline" => "8 أسابيع مع عروض أسبوعية لأصحاب المصلحة",
        "portfolio_evo_satisfaction" => "نسبة رضا 94٪ من منظمي النسخة التجريبية",
        "work_astral_desc" => "منصة تفاعلية لتخطيط الفعاليات تحول الأفكار إلى تجارب لا تُنسى.",
        "portfolio_estate_title" => "EstateFlow",
        "portfolio_estate_summary" => "منصة موحدة لإدارة العقارات والمدفوعات والصيانة.",
        "portfolio_estate_build" => "جمعنا تتبع العقود والطلبات والتقارير في لوحة واحدة مع صلاحيات للأدوار المختلفة.",
        "portfolio_estate_timeline" => "7 أسابيع من البداية حتى الإطلاق",
        "portfolio_estate_satisfaction" => "نسبة رضا 96٪ من فرق التشغيل",
        "work_signal_desc" => "نظام حديث لإدارة العقارات والمستأجرين والعمليات بكفاءة.",
        "footer_heading" => "هل أنت مستعد لبناء الإصدار القادم؟",
        "footer_desc" => "تعاون مع ديفاي لتجربة رقمية فاخرة.",
        "footer_cta" => "ابدأ مشروعًا",
        "label_email" => "البريد الإلكتروني",
        "label_password" => "كلمة المرور",
        "label_full_name" => "الاسم الكامل",
        "login_heading" => "مرحبًا بعودتك.",
        "login_subheading" => "سجّل الدخول للوصول إلى بوابة العملاء.",
        "login_button" => "تسجيل الدخول",
        "login_new_prompt" => "جديد في ديفاي؟",
        "login_new_link" => "إنشاء حساب",
        "error_invalid_credentials" => "بيانات الدخول غير صحيحة.",
        "register_heading" => "أنشئ بوابة العملاء الخاصة بك.",
        "register_subheading" => "انضم إلى ديفاي لبدء إرسال طلبات المشاريع.",
        "register_success" => "تم إنشاء الحساب بنجاح. يمكنك الآن تسجيل الدخول.",
        "register_error_required" => "جميع الحقول مطلوبة.",
        "register_error_exists" => "يوجد حساب بهذا البريد الإلكتروني بالفعل.",
        "register_error_failed" => "فشل التسجيل. يرجى المحاولة مرة أخرى.",
        "register_button" => "إنشاء حساب",
        "register_login_prompt" => "لديك حساب بالفعل؟",
        "register_login_link" => "تسجيل الدخول",
        "request_heading" => "ابدأ مشروعك القادم.",
        "request_subheading" => "أخبرنا عن رؤية منتجك وسنرد خلال 24 ساعة.",
        "request_success" => "تم إرسال طلب المشروع بنجاح.",
        "request_error" => "يرجى إدخال عنوان المشروع والتفاصيل.",
        "request_error_failed" => "تعذر إرسال طلبك. يرجى المحاولة مرة أخرى.",
        "request_title_label" => "اسم المشروع",
        "request_title_placeholder" => "مثال: إعادة تصميم SaaS فاخرة",
        "request_budget_label" => "الميزانية المتوقعة",
        "request_budget_placeholder" => "$10k - $30k",
        "request_timeline_label" => "الجدول الزمني المثالي",
        "request_timeline_placeholder" => "6-8 أسابيع",
        "request_details_label" => "تفاصيل المشروع",
        "request_details_placeholder" => "صف أهدافك وميزاتك وتوقعاتك.",
        "request_submit_button" => "إرسال الطلب",
        "contact_heading" => "تواصل معنا",
        "contact_subheading" => "أخبرنا عن أهداف مشروعك وسنرد خلال 24 ساعة.",
        "contact_name_label" => "الاسم",
        "contact_name_placeholder" => "الاسم الكامل",
        "contact_email_label" => "البريد الإلكتروني",
        "contact_email_placeholder" => "you@example.com",
        "contact_message_label" => "الرسالة",
        "contact_message_placeholder" => "اكتب ملخصًا سريعًا لما تحتاجه.",
        "contact_submit" => "إرسال الرسالة",
        "dashboard_welcome" => "مرحبًا، {name}.",
        "dashboard_subheading" => "تابع طلبات مشاريعك وحالتها الحالية.",
        "dashboard_new_request" => "طلب جديد",
        "dashboard_table_project" => "المشروع",
        "dashboard_table_budget" => "الميزانية",
        "dashboard_table_timeline" => "الجدول الزمني",
        "dashboard_table_status" => "الحالة",
        "dashboard_table_submitted" => "تاريخ الإرسال",
        "dashboard_empty" => "لا توجد طلبات بعد. أرسل موجز مشروعك الأول.",
        "admin_login_heading" => "دخول الإدارة",
        "admin_login_subheading" => "إدارة طلبات المشاريع الواردة.",
        "admin_login_button" => "تسجيل الدخول",
        "admin_dashboard_heading" => "نظرة الإدارة",
        "admin_dashboard_subheading" => "أدر كل الطلبات الواردة عبر المحفظة.",
        "admin_total_requests" => "{count} إجمالي الطلبات",
        "admin_status_updated" => "تم تحديث الحالة.",
        "admin_table_client" => "العميل",
        "admin_table_project" => "المشروع",
        "admin_table_budget" => "الميزانية",
        "admin_table_timeline" => "الجدول الزمني",
        "admin_table_status" => "الحالة",
        "admin_table_update" => "تحديث",
        "admin_empty" => "لا توجد طلبات مشاريع بعد.",
        "admin_save_button" => "حفظ",
        "status_submitted" => "تم الإرسال",
        "status_reviewing" => "قيد المراجعة",
        "status_in_progress" => "قيد التنفيذ",
        "status_completed" => "مكتمل"
    ]
];

function t(string $key, array $replace = []): string
{
    global $translations, $lang;
    $text = $translations[$lang][$key] ?? $translations["en"][$key] ?? $key;
    foreach ($replace as $placeholder => $value) {
        $text = str_replace("{" . $placeholder . "}", (string) $value, $text);
    }
    return $text;
}

function language_url(string $targetLang): string
{
    $uri = $_SERVER["REQUEST_URI"] ?? "index.php";
    $parts = parse_url($uri);
    $path = $parts["path"] ?? "index.php";
    $query = [];
    if (!empty($parts["query"])) {
        parse_str($parts["query"], $query);
    }
    $query["lang"] = $targetLang;
    $queryString = http_build_query($query);
    $fragment = isset($parts["fragment"]) ? "#" . $parts["fragment"] : "";
    return $path . ($queryString ? "?" . $queryString : "") . $fragment;
}
